version: '3'
services:
  blog-app:
    build: ./
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=0000
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DB=blog_db

  mongo:
    container_name: mongo
    image: mongo:6.0.2
    hostname: mongo
    environment:
      - MONGO_INITDB_DATABASE=blog_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=0000
    volumes:
      - ./.database/mongodb:/data/db
    ports:
      - '27017:27017'
